SET DATEFORMAT ymd
SET IDENTITY_INSERT CALENDRIER ON

INSERT INTO ETAT_CALENDRIER VALUES ('Actif');
INSERT INTO ETAT_CALENDRIER VALUES ('Inactif');
INSERT INTO ETAT_CALENDRIER VALUES ('Prévisionnel');
INSERT INTO ETAT_CALENDRIER VALUES ('Inscrit');

INSERT INTO ROLE_UTILISATEUR VALUES ('Utilisateur');

INSERT INTO UTILISATEUR VALUES (1, 'OLLIVIER', 'Stephane', 'contact@eni-ecole.fr', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'NACEUR', 'Luc', 'contact@eni-ecole.fr', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'THIBAUD', 'Cyril', 'contact@eni-ecole.fr', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'NOURRY', 'Beatrice', 'contact@eni-ecole.fr', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'OLIVIER', 'Stephane', 'contact@eni-ecole.fr', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'DIXNEUF', 'Baptiste', 'baptiste.dixneuf@gmail.com', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'LENOIR', 'Marius', 'marius.lenoir@hotmail.com', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');
INSERT INTO UTILISATEUR VALUES (1, 'PIRON', 'Axel', 'azerty', '$2a$10$TgTlrUH2IwlcKZea15Vzm.sUaWE4AiD9ioZYsVjn3d/6rPH7w/baO');

INSERT INTO TYPE_CONTRAINTE (TC_LIBELLE) VALUES ('SEMAINE_AFFILEE_ENTREPRISE');
INSERT INTO TYPE_CONTRAINTE (TC_LIBELLE) VALUES ('SEMAINE_AFFILEE_FORMATION');
INSERT INTO TYPE_CONTRAINTE (TC_LIBELLE) VALUES ('FORTE_ACTIVITE_ENTREPRISE');
INSERT INTO TYPE_CONTRAINTE (TC_LIBELLE) VALUES ('FAIBLE_ACTIVITE_ENTREPRISE');
INSERT INTO TYPE_CONTRAINTE (TC_LIBELLE) VALUES ('NON_DISPONIBILITE');
